Trade fee
cdump/investments pull request #28
Opened 2020-10-27 22:23 UTC by esemi

Сделал учёт комиссий в расчёте профита по сделкам
Всё в рублях, всё по курсам на соответствующие даты

Осталось:
- покрыть тестами prepare_trades_report раз уж у нас там такая важная калькуляция
- обновить пример отчёта тулы в ридми
-

2020-10-29 17:14 UTC, esemi commented
тестов добавил
@cdump пример оставлю обновить тебе, у меня нет такого красивого портфеля)

2020-11-13 09:46 UTC, esemi commented
Нашёл проблему в отображении маленькой комиссии на итоговом отчёте по сделкам
Связано с округлением до двух знаком, влияет только на отображение, расчёт прибыли/убытка корректный при этом
![image](https://user-images.githubusercontent.com/4115497/99058427-42c9f100-25ae-11eb-8cd2-8e12b94cbd03.png)

2020-11-18 03:52 UTC, esemi commented
@cdump пофиксил округление в отчёте (визуальная проблема была)
Можно ревьюшить)

билды упали ибо set-env таки запретили, пофиксил в соседнем МР

2020-11-18 03:58 UTC, esemi commented
Обновил пример отчёта в ридми

2020-11-21 17:11 UTC, esemi commented
@cdump пинг)

2020-11-22 17:28 UTC, cdump requested changes

2020-11-22 17:28 UTC, cdump commented on investments/ibtax/ibtax.py
> +    df = pandas.DataFrame(finished_trades, columns=finished_trades[0]._fields)  # noqa: WPS437
Вкусовщина, но я бы скорее сделал в FinishedTrade @property fields -> return self._fields и тут бы использовал его - и noqa уберется, и чуть больше абстракций над типом)
Но можно и оставить

2020-11-23 06:45 UTC, esemi commented on investments/ibtax/ibtax.py
> +    df = pandas.DataFrame(finished_trades, columns=finished_trades[0]._fields)  # noqa: WPS437
резонно, чёт упустил

2020-11-23 06:50 UTC, esemi commented on investments/trades_fifo.py
> +    @staticmethod
Вкусовщина, но на мой вкус если функция нужна и используется только внутри конкретного класса то её поближе и стоит положить. В данном случае знак определяется вообще глубоко в методах непубличного _TradesFIFO, потому туда её и завернул

2020-11-23 06:56 UTC, esemi commented on investments/trades_fifo.py
> +    @staticmethod
По моей практике такое потом проще удалять за неиспользование: одно дело рефачить публичное апи модуля и совсем другое - класса. Но это всё глубокое имхо, конечно

2020-11-23 07:25 UTC, esemi commented on investments/data_providers/cbr.py
> +        return self._df.loc[dt].item()
Долго копался с этим кодом и тестами, сейчас вспомню что как было.

upd:
Внутри `self._df.loc[]` индекс `DatetimeIndex`, у него внутри 
```
_scalar_type = Timestamp
_recognized_scalars = (datetime, np.datetime64)
```

Собственно если я в юнитах захочу вызвать get_rate по datetime.date то я получаю 
```
# unrecognized type
raise KeyError(key)
```

Видимо оттуда все эти танцы с бубном внутри get_rate с приведением типа. А datetime.date там на входе как родитель для всех datetime.*

Могу убрать сей код и фиксануть тесты, чтобы везде использовался datetime.datetime с минимальным временем внутри (ибо именно так в индексе лежит ключ)

2020-11-23 07:36 UTC, esemi commented on investments/data_providers/cbr.py
> +        return self._df.loc[dt].item()
@cdump сделал, глянь плиз

2020-11-24 17:14 UTC, merged