:fix: Increase precision for trades income/expenses/profit values
cdump/investments pull request #37
Opened 2021-01-21 20:49 UTC by esemi

Добавил точности в расчёт расхода/дохода и итогового профита. Разница в копейках, но имеет свойство накапливаться.
- перенёс все округления и из `prepare_report_*` функций в презентеры `show_report_*`
- убрал округление в verbose режиме
- зашил корректную калькуляцию расхода-дохода по сделке в тестах на `prepare_trades_report` - выше только презентер, главное проверить что никто до него не наокруглял.

2021-01-24 14:08 UTC, cdump requested changes

2021-01-24 14:08 UTC, cdump commented on tests/ibtax/prepare_trades_report.py
> +    res: dict = prepare_trades_report(test_case, ExchangeRatesRUB(Currency.USD), True).to_dict()
```>       res: dict = prepare_trades_report(test_case, ExchangeRatesRUB(Currency.USD), True).to_dict()                                                                                                                                   
E       TypeError: prepare_trades_report() takes 2 positional arguments but 3 were given
```

а все потому что тесты из этого файла не запускались (как и тесты ibdds) по `poetry run pytest -ra -v`
Нужно сделать
```
mv tests/ibtax/prepare_trades_report.py tests/ibtax/prepare_trades_report_test.py
mv tests/ibdds/show_report.py tests/ibdds/show_report_test.py
```

2021-01-24 14:08 UTC, cdump commented on tests/ibtax/prepare_trades_report.py
> +    assert list(map(lambda x: x.amount, res['profit_rub'].values())) == [
Тут аналогично комменту выше

2021-01-24 14:08 UTC, cdump commented on investments/ibtax/ibtax.py
> +        feed_presenter = apply_round_for_dataframe(feed_presenter, {'amount', 'amount_rub'}, 2)
Предлагаю сделать все округления за один вызов - не будут лишние deepcopy, да и выглядеть будет получше (это уже субъективно):

Вижу два варианта:
```
feed_presenter = apply_round_for_dataframe(feed_presenter, {'rate': 4, 'amount': 2, 'amount_rub': 2)
```
или
```
feed_presenter = apply_round_for_dataframe(feed_presenter, [({'rate'}, 4), ({'amount', 'amount_rub'}, 2)])
```

У каждого есть свои плюсы/минусы, поэтому какой выбрать - можно подумать

2021-01-24 17:27 UTC, esemi commented on tests/report_parsers/ib_test.py
> -Trades,Total,,Stocks,USD,,,,,,-57144.745,-25.563491343,57180.290364603,9.981873,-16.654,"""
для кейса не нужен же

2021-01-24 17:54 UTC, esemi commented on investments/ibtax/ibtax.py
> +        feed_presenter = apply_round_for_dataframe(feed_presenter, {'amount', 'amount_rub'}, 2)
Я бы хотел видеть скорее код типа этого
```
feed_presenter.apply_round({'rate'}, 4).apply_round({'amount', 'amount_rub'}, 2)
```
но чёт много писать для такой реализации)

Мапа в сигнатуре функции не очень радует. Давай избавимся от дипкопии внутри `apply_round_for_dataframe` в пользу копии до её вызова?

2021-01-24 18:11 UTC, esemi commented on investments/ibtax/ibtax.py
> +        feed_presenter = apply_round_for_dataframe(feed_presenter, {'amount', 'amount_rub'}, 2)
Порефачил - копий будет меньше
Погляди?)

2021-01-26 14:25 UTC, esemi commented on investments/ibtax/ibtax.py
> +        feed_presenter = apply_round_for_dataframe(feed_presenter, {'amount', 'amount_rub'}, 2)
@cdump пинг)

2021-01-27 17:46 UTC, merged