WIP: :sparkles: Released separate short report for simple 3-ndfl declarating process
cdump/investments pull request #41
Opened 2021-03-10 18:25 UTC by esemi

Сделал отображение короткого репорта по всем доходам сгрупированным по коду для подачи декларации 3-НДФЛ в упрощённом виде (не каждую сделку отдельно, а все вместе одним числом)

2021-03-10 21:12 UTC, esemi commented
@cdump глянь плиз, как время будет
Оч хочется иметь возможность в удобном виде выдавать отчёт для подачи 3НДФЛ
Следом попробую сделать выгрузку расчётов в pdf, чтобы прикладывать как пояснительную записку

2022-01-09 16:36 UTC, cdump requested changes

2022-01-09 16:36 UTC, cdump commented on investments/ibtax/ibtax.py
> +                income_trades = income_trades.round(2)
Без `--verbose` ругается:
```  
File ".../investments/ibtax/ibtax.py", line 276, in show_ndfl_report
    income_interests = income_interests.round(2)
AttributeError: 'int' object has no attribute 'round'
```

p.s. запускал после rebase твоей ветки на origin/master, но влиять не должно

2022-01-10 08:05 UTC, esemi commented on investments/ibtax/ibtax.py
> +                income_trades = income_trades.round(2)
давай пока оставим этот МР в WIP и вмержим остальные
насколько я помню, краткая версия 3НДФЛ не факт что нужна ещё, поскольку рядом етсь полная

2022-03-08 23:45 UTC, closed without merging